
SHOW_GRAPHICS = False


# LAYOUT SETTINGS
SCREENWIDTH  = 288
SCREENHEIGHT = 512
PIPEGAPSIZE  = 175 # gap between upper and lower part of pipe
BASEY        = SCREENHEIGHT * 0.79

# AGENT SETTINGS
T_BETWEEN_STATES = .1
CHECKPOINT_DT   = 5 * 60     # every 5 minutes
X_POS_AGENT  = 57
Y_MIN_AGENT  = 0                    # top of screen (0 = top)
Y_MAX_AGENT  = BASEY                # where player crashes into ground
Y_MAX_VELOCITY = 10
Y_MIN_VELOCITY = -9


# PIPE SETTINGS
# PERCENT_TOGETHER = 1
# PIPEGAPSIZE  = BASEY * (1 - PERCENT_TOGETHER/200)
PIPEHEIGHT = 320
PIPEGAPSIZE  = 100
HEIGHT_VARIATION = .5 # wrt room remaining

Y_MEAN_LPIPE = (BASEY + PIPEGAPSIZE)/2

Y_MAX_LPIPE = int(Y_MEAN_LPIPE + (BASEY-Y_MEAN_LPIPE) * (HEIGHT_VARIATION) / 2)
Y_MIN_LPIPE = int(Y_MEAN_LPIPE - (BASEY-Y_MEAN_LPIPE) * (HEIGHT_VARIATION) / 2)
X_MAX_PIPE = SCREENWIDTH - X_POS_AGENT


# Checkpointing and debugging
RESET_EPSILON_GREEDY = False
STATES_BETWEEN_LOG = 1
LOG = False

MAX_POINTS_PER_EPISODE = 100
EPISODES_PER_SEQUENCE = 20000
SEQUENCE_PER_PARAMETER = 2


#self.VALUES
LOAD = False
SAVE = True
LOAD_FILE = 'init'
